name       : os-prober
version    : 1.79
release    : 6
source     :
    - https://ftp.debian.org/debian/pool/main/o/os-prober/os-prober_1.79.tar.xz : abe6317d078c4e51e322e62036b6df4a698bfe80c5be110a08894841179810ee
license    : GPL-2.0-or-later
component  : system.boot
homepage   : https://joeyh.name/code/os-prober
summary    : Detects OSes available on the system
description: |
    os-prober detects other OSes available on a system and outputs the results in a generic machine-readable format.
build      : |
    %make
install    : |
    # Inspired by Arch Linux's os-prober package.

    install -Dm00755 os-prober linux-boot-prober -t $installdir/usr/bin
    install -Dm00755 newns -t $installdir/%libdir%/os-prober
    install -Dm00755 common.sh -t $installdir/usr/share/os-prober

    for dir in os-probes os-probes/mounted os-probes/init linux-boot-probes linux-boot-probes/mounted; do
        install -dm00755 $installdir/%libdir%/$dir
        cp -a $dir/common/* $installdir/%libdir%/$dir
        if [ -d $dir/x86 ]; then
            cp -a $dir/x86/* $installdir/%libdir%/$dir
        fi
    done
    install -Dm00755 os-probes/mounted/powerpc/20macosx -t $installdir/%libdir%/os-probes/mounted

    install -Dm00644 $pkgfiles/os-prober.tmpfiles $installdir/%libdir%/tmpfiles.d/os-prober.conf
